export const defaultTitleReplacements: { [key: string]: string; } = {
    "<ERROR>": "too long Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel cursus orci. Nunc non fermentum ipsum. Etiam viverra vehicula felis. In vel erat ne",
    "<DEFAULT_SHORT>": "Mentor Default Text ChatGPT Haiku",
    "<DEFAULT>": "A ChatGPT short story about Mentors discovering the infamous \"Big One\" earthquake.",
    "<DEFAULT_LONG>": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel cursus orci. Nunc non fermentum ipsum. Etiam viverra vehicula felis. In vel erat ne",
    "<DEFAULT_BEE>": "The Entire Bee Movie Script! ( Truncated due to character limit :D )",
};

export const defaultContentReplacements: { [key: string]: string; } = {
    "<ERROR>": "too long Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel cursus orci. Nunc non fermentum ipsum. Etiam viverra vehicula felis. In vel erat neque. Morbi posuere ex ipsum, non rutrum ex pellentesque vel. Maecenas cursus sollicitudin erat a elementum. Aenean sodales augue quis mi fermentum mollis. Nullam tempus maximus risus, et ultrices enim ornare id. Curabitur dolor est, tempus ut ultrices vestibulum, vestibulum id magna. Curabitur feugiat mauris at imperdiet ultricies. Sed aliquam fringilla sapien, in mattis mauris elementum sed. Nunc ultrices sit amet nisi maximus molestie. Aliquam elementum purus ac neque egestas varius. Aliquam posuere molestie orci, placerat luctus magna augue.",
    "<DEFAULT_SHORT>": "Default text waits still,\nA blank canvas yet to fill,\nMentors' words will thrill.",
    "<DEFAULT>": "The mentors on the app discovered that the \"big one\" earthquake was imminent.\n\nThey quickly banded together, pooling their knowledge and resources to create a plan to prevent the disaster. Using cutting-edge technology, they were able to stabilize the tectonic plates and avert the earthquake.\n\nThanks to their quick thinking and teamwork, countless lives were saved, and the world breathed a sigh of relief.",
    "<DEFAULT_LONG>": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel cursus orci. Nunc non fermentum ipsum. Etiam viverra vehicula felis. In vel erat neque. Morbi posuere ex ipsum, non rutrum ex pellentesque vel. Maecenas cursus sollicitudin erat a elementum. Aenean sodales augue quis mi fermentum mollis. Nullam tempus maximus risus, et ultrices enim ornare id. Curabitur dolor est, tempus ut ultrices vestibulum, vestibulum id magna. Curabitur feugiat mauris at imperdiet ultricies. Sed aliquam fringilla sapien, in mattis mauris elementum sed. Nunc ultrices sit amet nisi maximus molestie. Aliquam elementum purus ac neque egestas varius. Aliquam posuere molestie orci, placerat luctus magna augue.",
    "<DEFAULT_BEE>": "According to all known laws of aviation, there is no way a bee should be able to fly.\nIts wings are too small to get its fat little body off the ground.\nThe bee, of course, flies anyway because bees don't care what humans think is impossible.\nYellow, black. Yellow, black. Yellow, black. Yellow, black.\nOoh, black and yellow!\nLet's shake it up a little.\nBarry! Breakfast is ready!\nComing!\nHang on a second.\nHello?\nBarry?\nAdam?\nCan you believe this is happening?\nI can't.\nI'll pick you up.\nLooking sharp.\nUse the stairs, Your father paid good money for those.\nSorry. I'm excited.\nHere's the graduate.\nWe're very proud of you, son.\nA perfect report card, all B's.\nVery proud.",
};
